spring:
  application:
    name: analytics-service
  profiles:
    active: analytics
  config:
    import: 'configserver:'
  cloud:
    config:
      name: analytics-service,config-client
      username: spring_cloud_user
      password: '{cipher}6362306d7d4a54408fd3f23e90a0297d3a5f322fe3329e5c30316193ed4a5d2ee4e1c6f206cae3e247ad461c03ffe95b'

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service-1:8761/eureka,http://discovery-service-2:8762/eureka
  instance:
    lease-expiration-duration-in-seconds: 5
    lease-renewal-interval-in-seconds: 2
